#!/usr/bin/env bash
# AgentBus SessionStop hook — saves working state for cold-start context
# Full Phase 6e implementation (replaces stub)
# Reads most recent Claude Code JSONL, extracts last 3 exchanges,
# writes ~/.agent-bus/context/<project>/working-state.md

# Silent failure throughout — hook errors are noisy and unhelpful
set +e

PROJECT_NAME="${AGENT_BUS_PROJECT:-$(basename "$PWD")}"
CONTEXT_DIR="$HOME/.agent-bus/context/$PROJECT_NAME"
WORKING_STATE="$CONTEXT_DIR/working-state.md"

# Path encoding: /Users/ryaker/Dev/Trading → -Users-ryaker-Dev-Trading
encoded_path=$(echo "$PWD" | sed 's|/|-|g')
CLAUDE_PROJECT_DIR="$HOME/.claude/projects/$encoded_path"

# Find the most recent JSONL file
if [ ! -d "$CLAUDE_PROJECT_DIR" ]; then
  exit 0
fi

# Check sessions-index.json first (faster)
JSONL_FILE=""
if [ -f "$CLAUDE_PROJECT_DIR/sessions-index.json" ]; then
  JSONL_FILE=$(python3 -c "
import json, os, sys
try:
    index = json.load(open('$CLAUDE_PROJECT_DIR/sessions-index.json'))
    sessions = index if isinstance(index, list) else index.get('sessions', [])
    # Sort by updatedAt descending, find most recent
    sessions_sorted = sorted(sessions,
        key=lambda s: s.get('updatedAt', s.get('updated_at', '')),
        reverse=True)
    for s in sessions_sorted:
        sid = s.get('id') or s.get('sessionId')
        if sid:
            p = '$CLAUDE_PROJECT_DIR/' + sid + '.jsonl'
            if os.path.exists(p):
                print(p)
                break
except Exception:
    pass
" 2>/dev/null)
fi

# Fallback: find newest .jsonl by mtime
if [ -z "$JSONL_FILE" ]; then
  JSONL_FILE=$(find "$CLAUDE_PROJECT_DIR" -name "*.jsonl" -newer "$CLAUDE_PROJECT_DIR" 2>/dev/null \
    | xargs ls -t 2>/dev/null | head -1)
fi

if [ -z "$JSONL_FILE" ] || [ ! -f "$JSONL_FILE" ]; then
  exit 0
fi

# Extract last 3 user/assistant exchange pairs from JSONL
# JSONL format: one JSON object per line with {type, message: {role, content}}
mkdir -p "$CONTEXT_DIR"

python3 << PYEOF
import json, sys, os
from datetime import datetime, timezone

jsonl_file = "$JSONL_FILE"
output_file = "$WORKING_STATE"
project_name = "$PROJECT_NAME"

exchanges = []
try:
    with open(jsonl_file, 'r', encoding='utf-8', errors='replace') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                # Claude Code JSONL has type="user" or type="assistant" at top level
                # or nested under message.role
                role = None
                content = None

                if obj.get('type') in ('user', 'assistant'):
                    role = obj['type']
                    msg = obj.get('message', {})
                    if isinstance(msg.get('content'), str):
                        content = msg['content']
                    elif isinstance(msg.get('content'), list):
                        # Extract text blocks
                        parts = [b.get('text', '') for b in msg['content'] if isinstance(b, dict) and b.get('type') == 'text']
                        content = ' '.join(parts)
                    elif isinstance(msg, dict) and msg.get('role'):
                        role = msg['role']
                        c = msg.get('content', '')
                        content = c if isinstance(c, str) else str(c)[:500]

                if role and content:
                    exchanges.append({'role': role, 'content': str(content)[:800]})
            except (json.JSONDecodeError, KeyError):
                continue
except Exception as e:
    sys.exit(0)

# Take the last 6 entries (3 pairs) that alternate user/assistant
recent = exchanges[-6:] if len(exchanges) >= 6 else exchanges

if not recent:
    sys.exit(0)

# Write working-state.md
now = datetime.now(timezone.utc).isoformat()
with open(output_file, 'w', encoding='utf-8') as out:
    out.write(f"# Working State — {project_name}\n")
    out.write(f"_Captured: {now}_\n\n")
    out.write("## Last Session Exchanges\n\n")
    for ex in recent:
        role_label = "User" if ex['role'] == 'user' else "Assistant"
        content = ex['content'].strip()
        # Truncate long content
        if len(content) > 600:
            content = content[:600] + '...'
        out.write(f"**{role_label}:** {content}\n\n")
    out.write("---\n")
    out.write("_This file is auto-generated by AgentBus session-stop-profile hook._\n")

print(f"Working state written: {output_file}")
PYEOF

# Deregister this session from the bus so ClaudeCodeBridge knows we're gone
curl -s -X POST "http://localhost:8090/api/bus/deregister" \
  -H "Content-Type: application/json" \
  -d "{\"project\": \"$PROJECT_NAME\"}" > /dev/null 2>&1 || true

exit 0
